services:
  Jostkleigrewe\TelegramCoreBundle\Service\TelegramService:
    public: true
    autowire: true

  Jostkleigrewe\TelegramCoreBundle\Service\TelegramWebhookService:
    public: true
    autowire: true
